version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: financeer_postgres
    ports:
      - '6500:5432'
    volumes:
      - financeerpg:/var/lib/postgresql/data
    environment:
      # TODO: - Obviously change the data and move to dotenv
      POSTGRES_PASSWORD: "financeer"
      POSTGRES_PORT: 6500
      POSTGRES_DB: "financeer"
      POSTGRES_USER: "financeer"
volumes:
  financeerpg:
